export const LIST_INVOICES = "LIST_INVOICES";

export const FETCH_INVOICES = "FETCH_INVOICES";

export const CREATE_INVOICE = "CREATE_INVOICE";

export const CREATE_INVOICE_ERROR = "CREATE_INVOICE_ERROR";
